//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RERP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RERPEntities : DbContext
    {
        public RERPEntities()
            : base("name=RERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_category> tbl_category { get; set; }
        public virtual DbSet<tbl_color> tbl_color { get; set; }
        public virtual DbSet<tbl_company> tbl_company { get; set; }
        public virtual DbSet<tbl_sell> tbl_sell { get; set; }
        public virtual DbSet<tbl_size> tbl_size { get; set; }
        public virtual DbSet<tbl_sub_category> tbl_sub_category { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<tbl_expense_type> tbl_expense_type { get; set; }
        public virtual DbSet<tbl_expenses> tbl_expenses { get; set; }
        public virtual DbSet<tbl_product> tbl_product { get; set; }
        public virtual DbSet<tbl_product_details> tbl_product_details { get; set; }
        public virtual DbSet<tbl_sell_details> tbl_sell_details { get; set; }
    }
}
