//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int product_id { get; set; }
        public Nullable<int> com_id { get; set; }
        public string product_code { get; set; }
        public Nullable<int> product_category { get; set; }
        public Nullable<int> product_sub_category { get; set; }
        public string prod_name { get; set; }
        public string prod_type { get; set; }
        public Nullable<decimal> total_qty { get; set; }
        public Nullable<decimal> selling_total_qty { get; set; }
        public Nullable<decimal> remaining_total_qty { get; set; }
        public Nullable<decimal> total_buying_price { get; set; }
        public string dp { get; set; }
        public Nullable<decimal> sale_price { get; set; }
        public Nullable<decimal> buying_price { get; set; }
        public Nullable<decimal> last_price { get; set; }
        public Nullable<decimal> other_costing { get; set; }
        public string discount_type { get; set; }
        public Nullable<decimal> discont_rate { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_delete { get; set; }
        public Nullable<int> created_by { get; set; }
        public string created_pc { get; set; }
        public string created_ip { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> updated_by { get; set; }
        public string updated_pc { get; set; }
        public string updated_ip { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string manufacturername { get; set; }
        public string remarks { get; set; }
    }
}
