//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_company
    {
        public int com_id { get; set; }
        public string com_type { get; set; }
        public string company_name { get; set; }
        public string company_logo { get; set; }
        public string company_moto { get; set; }
        public string facebook_id { get; set; }
        public string telephone { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string website { get; set; }
        public string is_active { get; set; }
        public string is_delete { get; set; }
    }
}
