//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product_details
    {
        public int product_details_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string prod_code { get; set; }
        public Nullable<int> prod_size { get; set; }
        public Nullable<int> prod_color { get; set; }
        public Nullable<decimal> prod_qty { get; set; }
        public Nullable<decimal> prod_selling_qty { get; set; }
        public Nullable<decimal> prod_remain_qty { get; set; }
        public Nullable<decimal> prod_price { get; set; }
        public string prod_image { get; set; }
        public Nullable<int> created_by { get; set; }
        public string created_pc { get; set; }
        public string created_ip { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> updated_by { get; set; }
        public string updated_pc { get; set; }
        public string updated_ip { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string prod_remarks { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    }
}
