//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sub_category
    {
        public int sub_cate_id { get; set; }
        public int cate_id { get; set; }
        public string sub_cate_name { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<int> created_by { get; set; }
        public string created_pc { get; set; }
        public string created_ip { get; set; }
        public Nullable<int> updated_by { get; set; }
        public string updated_pc { get; set; }
        public string updated_ip { get; set; }
    }
}
