//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sell_details
    {
        public int sell_details_id { get; set; }
        public int sell_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public string item_code { get; set; }
        public Nullable<int> item_details_id { get; set; }
        public Nullable<int> color_id { get; set; }
        public Nullable<int> size_id { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> price { get; set; }
        public string remarks { get; set; }
        public Nullable<int> created_by { get; set; }
        public string created_pc { get; set; }
        public string created_ip { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> updated_by { get; set; }
        public string updated_pc { get; set; }
        public string updated_ip { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
