//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public int user_id { get; set; }
        public Nullable<int> com_id { get; set; }
        public string user_name { get; set; }
        public string user_mail { get; set; }
        public string pass { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string dp { get; set; }
        public string role { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<bool> remember_token { get; set; }
        public Nullable<int> created_by { get; set; }
        public string created_pc { get; set; }
        public string created_ip { get; set; }
        public Nullable<int> updated_by { get; set; }
        public string updated_pc { get; set; }
        public string updated_ip { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
