//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_expenses
    {
        public int expence_id { get; set; }
        public int type_id { get; set; }
        public string note { get; set; }
        public string remarks { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> ex_date { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    }
}
